# Generated by Django 5.0.2 on 2024-02-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(choices=[('Santé', 'Santé'), ('Pollution', 'Pollution'), ('Environnementale', 'Environnementale'), ('Hybride', 'Hybride')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'csv'), ('xml', 'xml'), ('excel', 'excel'), ('json', 'json'), ('png', 'png'), ('vis', 'vis'), ('tsv', 'tsv')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lien_acces', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_auteurs', models.TextField()),
                ('description_localite', models.TextField()),
                ('protocole_collecte', models.TextField()),
                ('frequence_maj', models.CharField(max_length=100)),
                ('documentation', models.TextField()),
                ('licence', models.BooleanField()),
                ('disponibilite', models.CharField(max_length=100)),
                ('nb_bd', models.IntegerField()),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('contact', models.CharField(max_length=255)),
                ('auteurs', models.ManyToManyField(related_name='ressources', to='portal.auteur')),
                ('categories', models.ManyToManyField(related_name='ressources', to='portal.categorie')),
                ('domaines', models.ManyToManyField(to='portal.domaine')),
                ('formats', models.ManyToManyField(to='portal.format')),
                ('localites', models.ManyToManyField(to='portal.localite')),
            ],
        ),
        migrations.CreateModel(
            name='LienAccesUtile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_lien', models.CharField(max_length=255)),
                ('lien', models.CharField(max_length=255)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_utiles', to='portal.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='BD_Reliee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nombre', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('contact', models.CharField(max_length=255)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bd_reliees', to='portal.ressource')),
            ],
        ),
    ]
