# Generated by Django 5.0.2 on 2024-02-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_reliee',
            name='auteur',
        ),
        migrations.AlterField(
            model_name='ressource',
            name='disponibilite',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='bd_reliee',
            name='auteur',
            field=models.ManyToManyField(related_name='BD_Reliee', to='portal.auteur'),
        ),
    ]
