# Generated by Django 5.0.2 on 2024-02-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_bd_reliee_auteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='description',
            new_name='content',
        ),
    ]
