# Generated by Django 5.0.2 on 2024-02-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_description_ressource_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='titre',
            new_name='title',
        ),
    ]
