# Generated by Django 5.0.2 on 2024-02-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_titre_ressource_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='title',
            new_name='titre',
        ),
    ]
