# Generated by Django 5.0.2 on 2024-02-24 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_content_ressource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_reliee',
            name='annee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='bd_reliee',
            name='auteur',
            field=models.ManyToManyField(blank=True, related_name='bd_reliees', to='portal.auteur'),
        ),
        migrations.AlterField(
            model_name='bd_reliee',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_reliee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_reliee',
            name='nombre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lienaccesutile',
            name='description_lien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description_auteurs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description_localite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='disponibilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='documentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='frequence_maj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='from_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='protocole_collecte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='to_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
